### ISSUE TITLE
Create the DataBuffer that converts lines of data from CarListener into one line and sends it to WorkHandeler

### ISSUE THREAD

**Issue by eirik1502** [SoftwareFactoryNTNU/BlackboxPi#8]
the json lines that is sent to WorkHandler is wrapped in a json object.
The lines from carListener may be as well.

The lines from CarListener contains only one data attribute with corresponding value.
We want the dataBuffer to convert lines of different datatypes to one line with all the data we are going to use. The line with all the data will be sent at a rate equal to GPS coordinate sample rate, approximetly one line per second.

**Comment by mathiasaap** [comment]
Vi snakket på tirsdag om at det kanskje ikke var nødvendig med en egen DataBuffer. Noen tanker?
